# Generated by Django 5.2.1 on 2025-05-25 10:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namect', models.CharField(max_length=100, verbose_name='Nom catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameC', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameE', models.CharField(max_length=80)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=25)),
                ('lot_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameF', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameST', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=800, verbose_name="Numéro d'étagère")),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(max_length=30, verbose_name='Salle')),
                ('armoire', models.CharField(max_length=30, verbose_name='Armoire')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameanl', models.CharField(max_length=80, verbose_name="Nom d'analyse")),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('min_norm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Norme minimale')),
                ('max_norm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Norme maximale')),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='Sona_Labo.methodology', verbose_name='Méthodologie')),
            ],
        ),
        migrations.CreateModel(
            name='MethodologyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sona_Labo.equipment')),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sona_Labo.methodology')),
            ],
        ),
        migrations.AddField(
            model_name='methodology',
            name='equipment',
            field=models.ManyToManyField(through='Sona_Labo.MethodologyRequirement', to='Sona_Labo.equipment'),
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameM', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Sona_Labo.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='Sona_Labo.modele'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('heure', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.client')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.lot')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.sampletype')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.shelf')),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='Sona_Labo.storagelocation', verbose_name='Emplacement de stockage'),
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('etagere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='Sona_Labo.shelf')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='Sona_Labo.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valeur')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Sona_Labo.analyse', verbose_name='Analyse')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Sona_Labo.sample', verbose_name='Échantillon')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'unique_together': {('analyse', 'sample')},
            },
        ),
    ]
