# Generated by Django 5.2.1 on 2025-05-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0002_alter_result_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Équipment'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Fabriquant'},
        ),
        migrations.AlterModelOptions(
            name='methodology',
            options={'verbose_name': 'Méthodologie'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Échantillon'},
        ),
        migrations.AlterModelOptions(
            name='sampletype',
            options={'verbose_name': 'Type d’Échantillon'},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name': 'Étagère'},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'verbose_name': 'Emplacement de stockage'},
        ),
        migrations.AddField(
            model_name='sampletype',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sample_types', to='Sona_Labo.category', verbose_name='Catégorie'),
            preserve_default=False,
        ),
    ]
