# Generated by Django 5.2.1 on 2025-05-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0003_alter_category_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodologyrequirement',
            options={'verbose_name': 'Exigence méthodologique'},
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du rapport')),
                ('analyse', models.ManyToManyField(related_name='reports', to='Sona_Labo.analyse', verbose_name='Analyse')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Sona_Labo.client', verbose_name='Client')),
                ('sample', models.ManyToManyField(related_name='reports', to='Sona_Labo.sample', verbose_name='Échantillon')),
            ],
        ),
    ]
