# Generated by Django 5.2.1 on 2025-05-28 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0004_alter_methodologyrequirement_options_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodologyrequirement',
            options={'verbose_name': 'Exigence Méthodologique'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Rapport'},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='analyse',
            name='methodology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='Sona_Labo.methodology', verbose_name='Méthodologie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Code client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nameC',
            field=models.CharField(max_length=30, verbose_name='Nom du client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='Sona_Labo.modele', verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='nameE',
            field=models.CharField(max_length=80, verbose_name="Nom de l'équipement"),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='emplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='Sona_Labo.storagelocation', verbose_name='Emplacement de stockage'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='etagere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='Sona_Labo.shelf', verbose_name='Étagère'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code du lot'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_name',
            field=models.CharField(max_length=50, verbose_name='Nom du lot'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='nameF',
            field=models.CharField(max_length=80, verbose_name='Nom du fabricant'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la méthodologie'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='methodologies', through='Sona_Labo.MethodologyRequirement', to='Sona_Labo.equipment', verbose_name='Équipements nécessaires'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='instruction',
            field=models.TextField(blank=True, help_text="Instructions pour l'utilisation de la méthodologie", null=True, verbose_name='Instructions de la méthodologie'),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre de la méthodologie'),
        ),
        migrations.AlterField(
            model_name='methodologyrequirement',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Sona_Labo.equipment', verbose_name='Équipement'),
        ),
        migrations.AlterField(
            model_name='methodologyrequirement',
            name='methodology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Sona_Labo.methodology', verbose_name='Méthodologie'),
        ),
        migrations.AlterField(
            model_name='methodologyrequirement',
            name='required',
            field=models.BooleanField(blank=True, default=True, help_text="Indique si l'équipement est obligatoire pour cette méthodologie", null=True, verbose_name='Obligatoire'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Sona_Labo.manufacturer', verbose_name='Fabriquant'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='nameM',
            field=models.CharField(max_length=80, verbose_name='Nom du modèle'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='heure',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.lot', verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='priority',
            field=models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=100, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.sampletype', verbose_name="Type d'échantillon"),
        ),
        migrations.AlterField(
            model_name='sample',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='Sona_Labo.shelf', verbose_name='Étagère'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volume (L)'),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='nameST',
            field=models.CharField(max_length=70, verbose_name="Nom du type d'échantillon"),
        ),
    ]
