# Generated by Django 5.2.1 on 2025-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0005_alter_methodologyrequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodology',
            name='equipment',
            field=models.ManyToManyField(related_name='methodologies', through='Sona_Labo.MethodologyRequirement', to='Sona_Labo.equipment', verbose_name='Équipements nécessaires'),
        ),
    ]
