# Generated by Django 5.2.1 on 2025-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0006_alter_methodology_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='Nameanl',
            field=models.CharField(max_length=80, unique=True, verbose_name="Nom d'analyse"),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='titre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Titre de la méthodologie'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du rapport'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sample',
            field=models.ManyToManyField(related_name='reports', to='Sona_Labo.sampletype', verbose_name='Échantillon'),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='nameST',
            field=models.CharField(max_length=70, verbose_name="Nom du type d'échantillon"),
        ),
    ]
