# Generated by Django 5.2.1 on 2025-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0007_alter_analyse_nameanl_alter_methodology_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletype',
            name='nameST',
            field=models.CharField(max_length=70, verbose_name="Nom du type d'échantillon"),
        ),
    ]
