# Generated by Django 5.2.1 on 2025-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0008_alter_sampletype_namest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletype',
            name='nameST',
            field=models.CharField(max_length=70, unique=True, verbose_name="Nom du type d'échantillon"),
        ),
    ]
