# Generated by Django 5.2.1 on 2025-05-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0009_alter_sampletype_namest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='sample',
            new_name='sample_type',
        ),
    ]
