# Generated by Django 5.2.1 on 2025-05-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0010_rename_sample_report_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Sona_Labo.client', verbose_name='Client'),
        ),
    ]
