# Generated by Django 5.2.1 on 2025-05-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sona_Labo', '0011_alter_report_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Unité'},
        ),
    ]
