"""
Django settings for LIMS project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-agj2-synu@#gd)%bq-89c9-twb!yym!kx2if40cdpp+yo)2os8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'Sona_Labo',
    'jazzmin',
    #'admin_interface',
    #'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #"import_export",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LIMS.urls'

TEMPLATES = [
    {
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LIMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Jazzmin settings

JAZZMIN_SETTINGS = {
    "site_title": "LIMS",
    "site_header": "LIMS",
    "site_brand": "Gestionne laboratoire",
    "site_logo": "img/sonv.png",
    "login_logo": None,
    "login_logo_dark": None,
    "site_icon": None,
    "welcome_sign": "Bienvenue sur le portail de gestion du laboratoire",
    "user_avatar": None,
    "related_modal_active": False,
    "search_model": "Sona_Labo.Sample",
    "copyright": "SONATRACH LABORATORY ",


     "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "sona_labo.client": "fas fa-user-injured",
        "sona_labo.category": "fas fa-tags",
        "sona_labo.sampletype": "fas fa-vial",
        "sona_labo.lot": "fas fa-boxes",
        "sona_labo.storagelocation": "fas fa-warehouse",
        "sona_labo.shelf": "fas fa-layer-group",
        "sona_labo.localisation": "fas fa-map-marker-alt",
        "sona_labo.sample": "fas fa-flask",
        "sona_labo.manufacturer": "fas fa-industry",
        "sona_labo.modele": "fas fa-cogs",
        "sona_labo.equipment": "fas fa-microscope",
        "sona_labo.methodology": "fas fa-project-diagram",
        "sona_labo.methodologyrequirement": "fas fa-tasks",
        "sona_labo.analyse": "fas fa-notes-medical",
        "sona_labo.result": "fas fa-vials",
        "sona_labo.report": "fas fa-file-medical",
    },
    "show_ui_builder": True,
    "dark_mode_theme": True,

    "order_with_respect_to": [
        "Sona_Labo.Sample",
        "Sona_Labo.Result",
        "Sona_Labo.Client",
        "Sona_Labo.Report",
        "Sona_Labo.Analyse",
        "sona_labo.sampletype",
        "sona_labo.methodology",
        "sona_labo.category",
        "sona_labo.equipment",
        "sona_labo.lot",
        "sona_labo.localisation",
        "sona_labo.methodologyrequirement"
        "sona_labo.storagelocation",
        "sona_labo.shelf",
        "sona_labo.modele",
        "sona_labo.manufacturer",
       
    # etc...
],
 

}